spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_chayuanshuangkou


  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          memberGoldsAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chayuanShuangkouGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chayuanShuangkouResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wisecrack:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          watchRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        memberGoldsAccounting:
          destination: memberGoldsAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        chayuanShuangkouGame:
          destination: chayuanShuangkouGame
          contentType: application/json
          producer:
            partitionCount: 1
        chayuanShuangkouResult:
          destination: chayuanShuangkouResult
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-chayuanshuangkou
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai-chayuanshuangkou
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        chayuanShuangkouGameRoom:
          destination: chayuanShuangkouGameRoom
          group: qipai-chayuanshuangkou
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wisecrack:
          destination: wisecrack
          contentType: application/json
          producer:
            partitionCount: 1
        watchRecord:
          destination: watchRecord
          contentType: application/json
          producer:
            partitionCount: 1
      
server:
  port: 2009
  tomcat:
    access-log-enabled: true
    access-log-pattern: '%a %h %A %p %U %t %H %m %r %s %b %D'
    basedir: ./
  #compression:
    #enabled: true
    #mime-types: application/json,application/xml,text/html,text/xml,text/plain
    #min-response-size: 1024

filepath:
  snapshotFileBasePath: /data/app/qipai_chayuanshuangkou/server1/snapshot
  jFileBasePath: /data/app/qipai_chayuanshuangkou/server1/journal
  
logging:
  config: classpath:spring-log.xml